version: 2.1

orbs:
  gradle: circleci/gradle@2.2.0

executors:
  gradle-executor:
    docker:
      - image: 'cimg/openjdk:16.0.1'

jobs:
  gradle_build:
    executor:gradle-executor
    steps:
      - checkout
      - run:
          name: Build Scala code with Gradle
          command: |
            echo "going to build with gradle"
            gradle wrapper
            gradle build
              
workflows:
  version: 1
  dev:
    jobs:
      - gradle_build 
